app:
  languages:
    fallback: russian
    lang-to-code:
      english: en
      german: de
      russian: ru
    lang-to-labels:
      german:
        chapter: Kapitel
        section: Abschnitt
        figure: Figur
        table: Tabelle
        tableofcontents: Inhaltsverzeichnis
      russian:
        chapter: Глава
        section: Раздел
        figure: Рис.
        table: Таблица
        tableofcontents: Оглавление
      english:
        chapter: Chapter
        section: Section
        figure: Fig.
        table: Table
        tableofcontents: Table of Contents
#logging.level.com.github.vlsergey: DEBUG