app:
  languages:
    fallback: russian
    lang-to-code:
      english: en
      german: de
      russian: ru
    lang-to-labels:
      german:
        chapter: Kapitel
        section: Abschnitt
        figure: Figur
        table: Tabelle
      russian:
        chapter: Глава
        section: Раздел
        figure: Рис.
        table: Таблица
      english:
        chapter: Chapter
        section: Section
        figure: Fig.
        table: Table